[package]
name = "rocket-jwt-demo"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = "0.5.0-rc.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }
serde_derive = { version = "1.0" }
jsonwebtoken = "8"
rocket-jwt = { path = "../.." }
